ServerEvents.recipes(event=>{
    event.remove([
        {
            id:'call_of_yucutan:wooden_tecpatl_recipe'
        },
        {
            id:'call_of_yucutan:wooden_spear_recipe'
        }
    ])
})