ServerEvents.recipes(event=>{
    event.remove([
        {id:'farmersplus:milling/bone'},
        {id:'twigs:bone_meal_from_seashells'},
        {id:'call_of_yucutan:elder_bone_meal'},
        {id:'farmersplus:milling/cobblestone'},
        {id:'farmersplus:milling/cobbled_deepslate'},
        {input:'#expert:standard_bonemeal',output:'minecraft:bone_meal'},
        {id:'farmersplus:cutting/apple_slice'},
        {id:'farmersplus:cutting/golden_apple_slice'}
    ])
    event.custom({type:'farmersplus:milling',ingredients:[{tag:'expert:standard_bonemeal'}],result:[{count:3,item:'minecraft:bone_meal'},{count:1,item:'minecraft:bone_meal',chance:0.25}]})
    event.replaceInput({
        output:'#expert:pastries'
    },    
        'minecraft:wheat',
        'farmersplus:wheat_flour')
    event.custom({type:'farmersplus:milling',ingredients:[{tag:'forge:cobblestone'}],result:[{count:1,item:'minecraft:gravel'}]})
})