ServerEvents.recipes(event=>{
    event.remove([{type:'pizzacraft:chopping_recipe'},
        {output:'/pizzacraft:(.*?)_knife/'},
        {output:'/pizzacraft:(.*?)_chopping_board/'},
        {id:'pizzacraft:oven'},
        {id:'pizzacraft:corn_flour'},
        {id:'pizzacraft:dough'},
        {id:'pizzacraft:farmersdelight/tomato'},
        {id:'pizzacraft:farmersdelight/onion'},
        {id:'pizzacraft:farmersdelight/cucumber'},
        {id:'pizzacraft:cooked_fish_fillet'}
    ])
})
