StartupEvents.registry('block',event=>{
    event.create('brick_1')
    .displayName('Barely Complete Daub With Bricks')
    .soundType('packed_mud')
    .hardness(1.0)
    .resistance(3)
    .requiresTool(false)
    .textureAll('expert:block/brick_1')
    .tagBlock('mineable/pickaxe')

    event.create('brick_2')
    .displayName('Somewhat Complete Daub With Bricks')
    .soundType('packed_mud')
    .hardness(1.25)
    .resistance(3)
    .requiresTool(false)
    .textureAll('expert:block/brick_2')
    .tagBlock('mineable/pickaxe')

    event.create('brick_3')
    .displayName('Almost Complete Daub With Bricks')
    .soundType('stone')
    .hardness(1.5)
    .resistance(4)
    .requiresTool(false)
    .textureAll('expert:block/brick_3')
    .tagBlock('mineable/pickaxe')

    event.create('brick_4')
    .displayName('Ready-To-Mortar Daub With Bricks')
    .soundType('stone')
    .hardness(1.75)
    .resistance(4)
    .requiresTool(true)
    .textureAll('expert:block/brick_4')
    .tagBlock('mineable/pickaxe')
})