
["Config Screen Settings"]
	#Enable or disable configuration screen to edit in live different Eruannie's mod settings.
	Config_Screen = false
	#Change the side in which the banner configuration will be displayed.
	Mirrored_Banner = false
	#Select the type of configuration button to display.
	#Allowed Values: BOOK, BANNER
	Button_Type = "BOOK"

