
[items]

	[items.bone_meal]
		#If tall flowers can be fertilized with Bone Meal to duplicate
		"Tall flower fertilizing" = false
		#If short flowers can be fertilized with Bone Meal to duplicate
		"Short flower fertilizing" = false

