"Show Enchanted Mob Hud" = false
#Disable Poison Mob Enchant Particle. [true / false]
"Disable Poison Particle" = true
#Disable Aura Render. [true / false]
"Disable Aura Render" = false
#Enable Old Style Animation. [true / false]
OldStyleAnimation = false

