
[Settings]
	enableVanillaIngredientStorages = true

[Storages]
	enableAppleBag = false
	enableBrownMushroomBag = true
	enableCocoaBeanBag = true
	enableCrimsonFungusBag = true
	enableGlowBerryBag = false
	enableGoldenAppleBag = false
	enableGoldenCarrotCrate = false
	enableEggBox = true
	enableKelpBlock = false
	enableRedMushroomBag = true
	enableSugarCaneBale = false
	enableSweetBerryBag = false
	enableWarpedFungusBag = true

