
["Remove Mouseover Highlight Configs"]
	#Enables 1 key press to toggle this mod functionality
	"Use key toggle" = false
	#Default State for Remove Mouseover Highlight - true = ON // false = OFF
	"Default State" = true
	#Always hide border for Barrier Blocks - true = ON // false = OFF
	"Make Barriers Borders Invisible" = false

